### ISSUE TITLE
BB runs great on localhost:8080 but not behind haproxy+ssl

### ISSUE THREAD

**Issue by xrd** [Glimesh/broadcast-box#42]
I'm having great success using bb on localhost:8080. But, when I put it on a server with haproxy in front, it will not let me see video. I cannot tell if the issue is with the publish or the playback. I see an webrtc error in the JS console, but that seems to appear when I'm using localhost as well. Is there a way to enable verbose logging on the server and get more information on the full flow?

**Comment by xrd** [comment]
I'm using the docker container but perhaps I'm better off using the binary?

**Comment by Sean-Der** [comment]
Hey @xrd 

I will work on making the logging better on the client + server. You need two things for this to work I bet.

* Run your docker container with `--net=host`
* Broadcast Box needs to know an IP that you are reachable. Try setting `INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP=true` the env variable

This is the `docker-compose.yml` I am using on siobud.com. Should we include this in the repo itself?

```
  broadcast-box:
    environment:
    - INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP=yes
    - INTERFACE_FILTER=eth0
    image: seaduboi/broadcast-box
    hostname: broadcast-box
    domainname: siobud.com
    container_name: broadcast-box
    network_mode: "host"
    privileged: true
    restart: always
```
